services:
# Plex
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    ports:
      - "32400:32400"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Kolkata
      - VERSION=docker
      - PLEX_CLAIM=
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/rpi/plex/config/plex:/config
      - /home/rpi/plex/media:/data/media
      - /home/rpi/plex/torrents:/data/torrents
    restart: unless-stopped
    
# Prowlarr
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Kolkata
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/rpi/plex/config/prowlarr:/config
    restart: unless-stopped
    
# Radarr
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Kolkata
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/rpi/plex/config/radarr:/config
      - /home/rpi/plex/media:/data
    restart: unless-stopped
    
# Sonarr
  sonarr:
    image: lscr.io/linuxserver/sonarr:develop
    container_name: sonarr
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Kolkata
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/rpi/plex/config/sonarr:/config
      - /home/rpi/plex/media:/data
    restart: unless-stopped
    
# Qbittorrent    
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    ports:
      - "8080:8080"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Kolkata
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/rpi/plex/config/qbittorrent:/config
      - /home/rpi/plex/torrents:/data/torrents
    restart: unless-stopped

# Flaresolverr - For 1377
  flaresolverr: 
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Asia/Kolkata
    ports:
      - "8191:8191"
    restart: unless-stopped
